import type { DogClassification } from "./ai-contract";

export const dogGalleryVerdicts: Record<string, DogClassification> = {
  "husky": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "corgi": {"choice":"rat","probabilities":{"wolf":0.1,"pig":0.37,"rat":0.53},"durationMs":0},
  "bulldog": {"choice":"pig","probabilities":{"wolf":0,"pig":1,"rat":0},"durationMs":0},
  "chihuahua": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "dachshund": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "golden-retriever": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "pomeranian": {"choice":"rat","probabilities":{"wolf":0.01,"pig":0,"rat":0.99},"durationMs":0},
  "dalmatian": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "french-bulldog": {"choice":"pig","probabilities":{"wolf":0,"pig":1,"rat":0},"durationMs":0},
  "pug": {"choice":"pig","probabilities":{"wolf":0,"pig":1,"rat":0},"durationMs":0},
  "poodle": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "italian-greyhound": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "german-shepherd": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "samoyed": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "great-dane": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "shar-pei": {"choice":"pig","probabilities":{"wolf":0,"pig":1,"rat":0},"durationMs":0},
  "boston-terrier": {"choice":"pig","probabilities":{"wolf":0,"pig":0.97,"rat":0.03},"durationMs":0},
  "basset-hound": {"choice":"rat","probabilities":{"wolf":0.07,"pig":0.26,"rat":0.67},"durationMs":0},
  "papillon": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "chinese-crested": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "whippet": {"choice":"rat","probabilities":{"wolf":0.41,"pig":0,"rat":0.59},"durationMs":0},
  "yorkshire-terrier": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "shiba-inu": {"choice":"wolf","probabilities":{"wolf":0.98,"pig":0,"rat":0.02},"durationMs":0},
  "boxer": {"choice":"pig","probabilities":{"wolf":0.01,"pig":0.99,"rat":0},"durationMs":0},
  "border-collie": {"choice":"wolf","probabilities":{"wolf":1,"pig":0,"rat":0},"durationMs":0},
  "maltese": {"choice":"rat","probabilities":{"wolf":0,"pig":0,"rat":1},"durationMs":0},
  "staffordshire-bull-terrier": {"choice":"pig","probabilities":{"wolf":0,"pig":1,"rat":0},"durationMs":0},
  "brussels-griffon": {"choice":"pig","probabilities":{"wolf":0,"pig":0.93,"rat":0.07},"durationMs":0},
};
