import type { DogClassification } from "./ai-contract";

export const dogGalleryVerdicts: Record<string, DogClassification> = {
  husky: { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  corgi: { choice: "pig", probabilities: { wolf: 0, pig: 1, rat: 0 }, durationMs: 0 },
  bulldog: { choice: "pig", probabilities: { wolf: 0, pig: 1, rat: 0 }, durationMs: 0 },
  chihuahua: { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  dachshund: { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  "golden-retriever": { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  "pomeranian": {"choice": "rat", "probabilities": {"wolf": 0, "pig": 0, "rat": 1}, "durationMs": 0},
  "dalmatian": {"choice": "wolf", "probabilities": {"wolf": 1, "pig": 0, "rat": 0}, "durationMs": 0},
  "french-bulldog": {"choice": "pig", "probabilities": {"wolf": 0, "pig": 1, "rat": 0}, "durationMs": 0},
  "pug": {"choice": "pig", "probabilities": {"wolf": 0, "pig": 1, "rat": 0}, "durationMs": 0},
  "poodle": {"choice": "rat", "probabilities": {"wolf": 0, "pig": 0, "rat": 1}, "durationMs": 0},
  "italian-greyhound": {"choice": "rat", "probabilities": {"wolf": 0, "pig": 0, "rat": 1}, "durationMs": 0},
  "german-shepherd": { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  samoyed: { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  "great-dane": { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  "shar-pei": { choice: "pig", probabilities: { wolf: 0, pig: 1, rat: 0 }, durationMs: 0 },
  "boston-terrier": { choice: "pig", probabilities: { wolf: 0, pig: 0.96, rat: 0.04 }, durationMs: 0 },
  "basset-hound": { choice: "rat", probabilities: { wolf: 0, pig: 0.45, rat: 0.55 }, durationMs: 0 },
  papillon: { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  "chinese-crested": { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  whippet: { choice: "rat", probabilities: { wolf: 0, pig: 0.02, rat: 0.98 }, durationMs: 0 },
  "yorkshire-terrier": { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  "shiba-inu": { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  boxer: { choice: "pig", probabilities: { wolf: 0, pig: 1, rat: 0 }, durationMs: 0 },
  "border-collie": { choice: "wolf", probabilities: { wolf: 1, pig: 0, rat: 0 }, durationMs: 0 },
  maltese: { choice: "rat", probabilities: { wolf: 0, pig: 0, rat: 1 }, durationMs: 0 },
  "staffordshire-bull-terrier": { choice: "pig", probabilities: { wolf: 0, pig: 0.96, rat: 0.04 }, durationMs: 0 },
  "brussels-griffon": { choice: "pig", probabilities: { wolf: 0, pig: 0.68, rat: 0.32 }, durationMs: 0 },
};
