import type { Verdict } from "./game";

// Generated once with the current Jev rules. Gallery inputs are immutable, so
// shipping their verdicts avoids repeat model calls and makes selection instant.
export const galleryVerdicts: Record<string, Verdict> = {
  "caesar": {"id":"caesar","choice":"salad","probabilities":{"soup":0,"salad":1,"sandwich":0},"durationMs":0},
  "cereal": {"id":"cereal","choice":"soup","probabilities":{"soup":1,"salad":0,"sandwich":0},"durationMs":0},
  "burrito": {"id":"burrito","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "baozi": {"id":"baozi","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "biryani": {"id":"biryani","choice":"salad","probabilities":{"soup":0,"salad":1,"sandwich":0},"durationMs":0},
  "falafel": {"id":"falafel","choice":"salad","probabilities":{"soup":0,"salad":0.95,"sandwich":0.05},"durationMs":0},
  "gazpacho": {"id":"gazpacho","choice":"soup","probabilities":{"soup":1,"salad":0,"sandwich":0},"durationMs":0},
  "greek-salad": {"id":"greek-salad","choice":"salad","probabilities":{"soup":0,"salad":1,"sandwich":0},"durationMs":0},
  "hot-dog": {"id":"hot-dog","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "burger": {"id":"burger","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "lasagna": {"id":"lasagna","choice":"sandwich","probabilities":{"soup":0,"salad":0.08,"sandwich":0.92},"durationMs":0},
  "pho": {"id":"pho","choice":"soup","probabilities":{"soup":1,"salad":0,"sandwich":0},"durationMs":0},
  "mac-and-cheese": {"id":"mac-and-cheese","choice":"salad","probabilities":{"soup":0,"salad":1,"sandwich":0},"durationMs":0},
  "nachos": {"id":"nachos","choice":"sandwich","probabilities":{"soup":0,"salad":0.26,"sandwich":0.74},"durationMs":0},
  "ice-cream-sandwich": {"id":"ice-cream-sandwich","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "spaghetti": {"id":"spaghetti","choice":"salad","probabilities":{"soup":0.01,"salad":0.97,"sandwich":0.02},"durationMs":0},
  "ramen": {"id":"ramen","choice":"soup","probabilities":{"soup":1,"salad":0,"sandwich":0},"durationMs":0},
  "tacos": {"id":"tacos","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "sushi": {"id":"sushi","choice":"sandwich","probabilities":{"soup":0,"salad":0.03,"sandwich":0.97},"durationMs":0},
  "pizza": {"id":"pizza","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "cheesecake": {"id":"cheesecake","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "chicken-noodle": {"id":"chicken-noodle","choice":"soup","probabilities":{"soup":1,"salad":0,"sandwich":0},"durationMs":0},
  "waffle": {"id":"waffle","choice":"sandwich","probabilities":{"soup":0,"salad":0.18,"sandwich":0.82},"durationMs":0},
  "avocado-toast": {"id":"avocado-toast","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "dumplings": {"id":"dumplings","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "chicken-pot-pie": {"id":"chicken-pot-pie","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "brownie": {"id":"brownie","choice":"salad","probabilities":{"soup":0,"salad":0.8,"sandwich":0.2},"durationMs":0},
  "salmon-nigiri": {"id":"salmon-nigiri","choice":"sandwich","probabilities":{"soup":0,"salad":0,"sandwich":1},"durationMs":0},
  "loaded-fries": {"id":"loaded-fries","choice":"salad","probabilities":{"soup":0,"salad":0.96,"sandwich":0.04},"durationMs":0},
  "berry-smoothie": {"id":"berry-smoothie","choice":"soup","probabilities":{"soup":0.99,"salad":0.01,"sandwich":0},"durationMs":0},
};
